version: "3.8"

volumes:
  kafka1_volume:
  kafka2_volume:
  kafka3_volume:
  zookeeper_volume:

services:
  kowl:
    image: quay.io/cloudhut/kowl
    restart: on-failure
    hostname: kowl
    ports:
      - 8080:8080
    environment:
      - KAFKA_BROKERS=kafka1:29091,kafka2:29092,kafka3:29093
    depends_on:
      - kafka1
      - kafka2
      - kafka3

  zookeeper:
    image: confluentinc/cp-zookeeper
    healthcheck:
      test: echo stat | nc localhost 2181
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    environment:
      - ZOOKEEPER_SERVER_ID=1
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_INIT_LIMIT=5
      - ZOOKEEPER_SYNC_LIMIT=2
      - ZOOKEEPER_SERVERS=zookeeper:2888:3888
    volumes:
      - type: volume
        target: /var/lib/zookeeper/data
        source: zookeeper_volume

  kafka1:
    image: confluentinc/cp-kafka
    hostname: kafka1
    healthcheck:
      test: ps augwwx | egrep [S]upportedKafka
    ports:
      - "9091:9091"
    depends_on:
      - zookeeper
    environment:
      - KAFKA_LISTENERS=INSIDE://0.0.0.0:29091, OUTSIDE://0.0.0.0:9091
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka1:29091, OUTSIDE://localhost:9091
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT, OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=1
      - BOOTSTRAP_SERVERS=kafka1:29091,kafka2:29092,kafka3:29093
    volumes:
      - type: volume
        target: /var/lib/kafka/data
        source: kafka1_volume

  kafka2:
    image: confluentinc/cp-kafka
    healthcheck:
      test: ps augwwx | egrep [S]upportedKafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_LISTENERS=INSIDE://0.0.0.0:29092, OUTSIDE://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka2:29092, OUTSIDE://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT, OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=2
      - BOOTSTRAP_SERVERS=kafka1:29091,kafka2:29092,kafka3:29093
    volumes:
      - type: volume
        target: /var/lib/kafka/data
        source: kafka2_volume

  kafka3:
    image: confluentinc/cp-kafka
    healthcheck:
      test: ps augwwx | egrep [S]upportedKafka
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      - KAFKA_LISTENERS=INSIDE://0.0.0.0:29093, OUTSIDE://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka3:29093, OUTSIDE://localhost:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT, OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=3
      - BOOTSTRAP_SERVERS=kafka1:29091,kafka2:29092,kafka3:29093
    volumes:
      - type: volume
        target: /var/lib/kafka/data
        source: kafka3_volume
